### ISSUE TITLE
short opts

### ISSUE THREAD

**Issue by wulfy23** [alerighi/modbus-sniffer#10]
hey dude, thanks for the tool, super helpful for me...

I don't write C, but short opt for --interval -> -t didn't work for me... maybe my syntax was wrong or something on this line here? missing t?

```
 while ((opt = getopt_long(argc, argv, "ho:p:s:P:S:b:l", long_options, NULL)) >= 0) {
```

thanks again!

**Comment by alerighi** [comment]
Hi, 

you are right, the "-t" option is missing in the getopt_long function call. I've fixed it in the last release, among other minor improvements. 

Thanks for your feedback!
