### ISSUE TITLE
Realtime readable output

### ISSUE THREAD

**Issue by frankvandenhurk** [alerighi/modbus-sniffer#3]
I would like to send all sniffed data to MQTT (in a human readable form).  Would it be possible to pipe the output to Wireshark or tshark to get an almost realtime human readable output, so I can pick that up and send it to MQTT?

**Comment by alerighi** [comment]
Unfortunately as for now there is not a way to pipe the file directly to `stdout`. It's surely a feature that would be useful and I may consider implementing it.

As a workaround for now what you can do is to launch the program, then in another terminal launch`tail -f` to read the output file in realtime and pipes the output in Wireshark or another application. In the past I did use this configuration and it should work.

**Comment by alerighi** [comment]
With my last commit I introduced the changed written above. Now by default the output goes to stdout, and can be piped to other programs. Of course you can still use the `--output` option to write the output to a file (or pipe into it). 

The program no longer manages an output directory: that operation can be done (better) with other tools, such as `logrotate`, that can also do things like compress the output files or send them via email.

**Comment by frankvandenhurk** [comment]
nice, tnx!
