### ISSUE TITLE
ioctl get: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by frankvandenhurk** [alerighi/modbus-sniffer#4]
Finally recieved my USB RS-485 dongle. Driver is loaded:

[   16.285543] usbcore: registered new interface driver ch341
[   16.285606] usbserial: USB Serial support registered for ch341-uart
[   16.285648] ch341 1-1.1:1.0: ch341-uart converter detected
[   16.288046] usb 1-1.1: ch341-uart converter now attached to ttyUSB0

When I start the sniffer, I get the following error:

frank@odroid:~/modbus-sniffer$ ./sniffer -p /dev/ttyUSB0
output file: -
serial port: /dev/ttyUSB0
port type: 8N1 9600 baud
time interval: 1500
starting modbus sniffer
ioctl get: Inappropriate ioctl for device

Any idea what causes this error?

I also tried https://github.com/j123b567/SerialPCAP , this one is working (so the USB device is working) but I don't like the bulkiness of te mono framework.

**Comment by alerighi** [comment]
It recently merged a pull request that introduced an ioctl to set the device unbuffered. It may be that not all devices support that mode, however. 

I will update the tool to make that call optional with a command line flag as soon as possible. For now you can comment out the ioctl from the code.

**Comment by frankvandenhurk** [comment]
Tnx again for the quick reply. I can confirm that when I remove the following lines:

```
    if (ioctl(fd, TIOCGSERIAL, &serial) < 0)
        DIE("ioctl get");
    serial.flags |= ASYNC_LOW_LATENCY;
    if (ioctl(fd, TIOCSSERIAL, &serial) < 0)
        DIE("ioctl set");
```

it is working perfectly.

**Comment by alerighi** [comment]
I should have solved it with the latest release. Now this is an option that is available trough the `--low-latency` command line switch. Moreover if activated it will only print an error if it can't be activated, but continue anyway the execution in normal mode.
