### ISSUE TITLE
Usage of interval-parameter

### ISSUE THREAD

**Issue by adrha** [alerighi/modbus-sniffer#5]
Thank you for this cool piece of code!

I'm currently wondering, how the defined interval is affecting the data.
I built a test-setup with two slaves operating in half-duplex at 9600baud and had to set the interval to 2000ms in order to log the packets correctly.
This works perfectly but I'm about to install it in a bigger setup with approx. 14 slaves on a single bus, where the bus-messages might not be in coordinated intervals of 2000ms or 1500ms.
What is the internal function of the interval? Might it cut a message in half, if the interval is set on a too low value?

Thx!

**Comment by alerighi** [comment]
> What is the internal function of the interval

As now, the software doesn't really understand the Modbus protocol. That is it doesn't interpret the Modbus messages and thus know when a message will stop by reading its length. Unfortunately the Modbus packet doesn't have a length field, so to know the length of the message you would need to interpret all the function codes, that is outside the scope of this software, that does a capture at the physical layer and doesn't have knowledge of the content of the Modbus packets. 

The tool simply waits for a timeout where no communication happens to know that a device has done sending the message. The Modbus RTU physical specification impose that message frames are separated by a silent interval of at least 3.5 character times, and that is what the software uses to know when a new message starts. It also says that between two characters in a frame doesn't pass more than 1.5 character time (you can get more information [here](https://www.modbus.org/docs/Modbus_over_serial_line_V1_02.pdf) at page 14). Note that the character time depends on the particular speed (baud rate) used, and that devices may not follow the standard 100%. 

If you have more slave devices on a serial bus and the devices respect the protocol, assuming no two device communicate at the same time, it should work without any issues. 

Finally to have more precise timing and thus have more success you may need to activate the low-latency mode (requires root privileges) and give the sniffer process an higher priority (nice level).

**Comment by adrha** [comment]
Alright that makes sense! Thank you for the details and the explenation!
I've now seen that the unit of the interval in your software is in microseconds and not milliseconds as I first thought.
I'm closing the issue.
