### ISSUE TITLE
Break  and failed CRC after every 32 Bytes on long response

### ISSUE THREAD

**Issue by drame1499** [alerighi/modbus-sniffer#9]
Hi,

I'm trying to log some modbus traffic between my huawei inverter and smart meter. 
It works only partly.
The requests from the inverter to the smart meter and the request and responses to/from the battery decode correctly.
But the response from the smartmeter is really long (i think 80 registers so 160 bytes requested, 165 bytes in total).
The output is like this 
captured packet 206: length = 8, CRC: 32A7 = 32A7 [OK]
        DUMP:  0B 03 08 36 00 50 A7 32
captured packet 207: length = 32, CRC: 5AC9 = 439A [FAIL]
captured packet 208: length = 32, CRC: 151A = C3CD [FAIL]
captured packet 209: length = 32, CRC: 0E0A = 4366 [FAIL]
captured packet 210: length = 32, CRC: C808 = C29A [FAIL]
captured packet 211: length = 32, CRC: E08C = 4233 [FAIL]
captured packet 212: length = 5, CRC: BC28 = 2853 [FAIL]

I tried playing around with the --interval parameter but I can't get it to decode properly.
I also have a hard time finding the correct documentation for all the serial port functions. 

Maybe you can guide me what to adjust so that the response paket is read as a whole?

Best regards, 
Philipp

**Comment by alerighi** [comment]
Hi Philipp,

this tools works "best effort" to try to reconstruct the packet. For it to work, it assumes that the maximum interval between two bytes sent from the device is inferior to the interval passed to `--interval` parameter. 

This of course may vary depending on the kind of the device. A more correct (but complex!) solution would have been to interpret each Modbus packet. Unfortunately, Modbus doesn't have the packet length in its header, thus to get the actual packet length there are two ways, one would be to inspect the function code, and then knowing the semantic of the packet know its length, the second would be to decode the packet as a sliding window till the CRC matches. Unfortunately both solutions have their cons, in particular they don't work so well in case of corrupted packets.

Returning to your problem, there could be two reasons for this behavior. One reason being that the device sends the bytes with a (long) pause between every 32 bytes (maybe it buffers internally the serial port), the other that the serial converter you are using has an internal buffer of 32 bytes. On Linux the program tries to set the serial port to raw non buffered mode, but the serial converter may have a buffer inside. 

What I would suggest is:
- try to increase the `--interval` parameter
- try another serial converter (I had success with a Raspberry Pi integrated serial port)

Best regards,
Alessandro

**Comment by alerighi** [comment]
Closing since no further activity.
